// src/routes/(auth)/Badge.svelte
<script lang="ts">
	export let title: string;
	export let hue: number;
</script>

<span class="badge text-md inline-flex rounded-full px-3 font-medium" style="--color-hue: {hue}">
	{title}
</span>

<style lang="postcss">
	.badge {
		color: var(--color-12);
		background-color: var(--color-3);
	}
	@media (prefers-color-scheme: dark) {
		.badge {
			color: var(--color-0);
			background-color: var(--color-9);
		}
	}
</style>

// components/Badge.vue
<script lang="ts" setup>
import { Color } from "~~/lib/types";

const props = defineProps<{
    title: string;
    color: Color;
}>();
</script>

<template>
    <span
        :class="[
            'px-3 inline-flex text-md font-medium rounded-full',
            `bg-${color}-300 dark:bg-${color}-600`,
            `text-${color}-900 dark:text-white`,
        ]"
    >
        {{ title }}
    </span>
</template>
