// src/lib/components/RemoveButton.svelte
<script lang="ts">
	import { invalidate } from '$app/navigation';
	import { page } from '$app/stores';
	import type { GiftItem } from '$lib/db/schema/gift-item';
	import Icon from '@iconify/svelte';
	import toast from 'svelte-french-toast';

	export let id: GiftItem['id'];
	export let name: GiftItem['name'];

	const removeItem = async () => {
		const value: boolean = confirm('Are you sure?');

		if (value) {
			const formData = new FormData();
			formData.set('id', id);

			await toast
				.promise(
					fetch($page.url, {
						method: 'DELETE',
						body: formData
					}),
					{
						loading: 'Removing...',
						success: `Removed '${name}' successfully!`,
						error: `Removing item was not successful!`
					}
				)
				.then(() => {
					invalidate($page.url);
				});
		}
	};
</script>

<button
	class="cursor-pointer font-normal text-danger-500 hover:text-danger-700 dark:text-danger-600 dark:hover:text-danger-800"
	on:click={removeItem}
>
	<Icon icon="solar:trash-bin-2-line-duotone" class="block h-6 w-6" />
</button>

// components/RemoveButton.vue
<script lang="ts" setup>
import { useGiftItemStore } from "~~/stores/gift-item";
import { GiftItem } from "~~/lib/types";
import { useToast } from "vue-toastification/dist/index.mjs";

const giftItemStore = useGiftItemStore();

const toast = useToast();
const online = useOnline();

interface Props {
    item: GiftItem;
}

const props = defineProps<Props>();

const removeItem = async () => {
    const value: boolean = confirm("Are you sure?");

    if (value) {
        try {
            if (!online.value) throw new Error("Not online");

            await giftItemStore.removeItem(props.item.id);

            toast.success(`Removed '${props.item.name}' successfully!`);
        } catch (error) {
            console.error(error);
            toast.error(
                `Removing item was not successful! Reason: ${error.message}`
            );
        }
    }
};
</script>

<template>
    <a
        class="cursor-pointer font-normal text-danger-500 dark:text-danger-600 hover:text-danger-700 dark:hover:text-danger-800"
        @click="() => removeItem()"
    >
        <Icon name="ph:trash-bold" class="h-6 w-6" />
    </a>
</template>
