// src/routes/(auth)/TableRow.svelte
<script lang="ts">
	import { invalidate } from '$app/navigation';
	import { page } from '$app/stores';
	import EditButton from '$lib/components/EditButton.svelte';
	import RemoveButton from '$lib/components/RemoveButton.svelte';
	import { formatLink } from '$lib/utils/link';
	import { formatPrice } from '$lib/utils/price';
	import { createSwitch, melt, type CreateSwitchProps } from '@melt-ui/svelte';
	import toast from 'svelte-french-toast';
	import type { PageData as OverviewData } from '../../routes/(auth)/$types';
	import type { PageData as IdeasData } from '../../routes/(auth)/ideas/$types';
	import type { PageData as WishData } from '../../routes/(auth)/wish-list/$types';
	import MarkdownDisplay from '$lib/components/MarkdownDisplay.svelte';

	type EditGiftItem = (IdeasData['ideaList'][string] | WishData['wishList'])[number];
	type GiftItem = EditGiftItem | OverviewData['overviewList'][string][number];

	export let formData: IdeasData['formData'] | WishData['formData'] | undefined = undefined;
	export let currentUserGroups:
		| IdeasData['currentUserGroups']
		| WishData['currentUserGroups']
		| undefined = undefined;
	export let users: IdeasData['users'] | undefined = undefined;

	export let item: GiftItem;
	export let allowPurchased = false;
	export let allowEdit = false;

	const switchPurchased: CreateSwitchProps['onCheckedChange'] = ({ next }) => {
		const formData = new FormData();
		formData.set('id', item.id);
		formData.set('purchased', String(next));

		toast
			.promise(
				fetch($page.url, {
					method: 'PATCH',
					body: formData
				}),
				{
					loading: 'Saving...',
					success: `Changed purchase status of '${item.name}' successfully!`,
					error: `Saving purchase status was not successful!`
				}
			)
			.then(() => {
				invalidate($page.url);
			});
		return next;
	};

	const {
		elements: { root, input },
		states: { checked: isPurchased }
	} = createSwitch({
		defaultChecked: 'purchased' in item && item.purchased,
		onCheckedChange: switchPurchased
	});
</script>

<tr
	class="group border-b border-gray-200 last:border-none dark:border-gray-700 {'purchased' in
		item && $isPurchased
		? 'decoration-current line-through decoration-2 opacity-30'
		: ''}"
>
	<td class=" min-h-4rem px-6 py-4">
		<h3 class="text-sm font-medium text-gray-900 dark:text-gray-100">
			{item.name}
		</h3>
		<!-- FIXME: <MarkdownDisplay v-if="item.notes" class="min-w-full text-gray-500 dark:text-gray-400">
			{item.notes}
		</MarkdownDisplay> -->
		{#if item.notes}
			<MarkdownDisplay class="min-w-full text-gray-500 dark:text-gray-400">
				<p>{item.notes}</p>
			</MarkdownDisplay>
		{/if}
	</td>
	<td>
		<span class="whitespace-nowrap px-6 py-4 text-sm text-gray-500 dark:text-gray-400">
			{formatPrice(item.price)}
		</span>
	</td>
	<td>
		{#if item.link}
			<a
				href={item.link}
				target="_blank"
				rel="noopener noreferrer"
				class="inline-block w-full cursor-pointer overflow-hidden overflow-ellipsis whitespace-nowrap px-6 py-4 text-sm font-normal text-primary-500 underline hover:text-primary-700"
			>
				{formatLink(item.link)}
			</a>
		{/if}
	</td>
	<!-- TODO: -->
	<!-- <td class="flex items-center px-6 py-3">
                <div class="flex-shrink-0 h-10 w-10">
                    <img
                        v-if="item.pic"
                        class="h-10 w-10 rounded-md"
                        :src="item.pic[0].url"
                        alt=""
                    />
                </div>
            </td> -->
	{#if 'purchased' in item && allowPurchased}
		<td class=" px-6 py-3">
			<button
				use:melt={$root}
				class="relative inline-flex h-6 w-11 items-center rounded-full {$isPurchased
					? 'bg-success-500'
					: 'bg-gray-200 dark:bg-gray-400'}"
			>
				<span class="sr-only">Item purchased</span>
				<span
					class="inline-block h-4 w-4 transform rounded-full bg-white dark:bg-gray-100 {$isPurchased
						? 'translate-x-6'
						: 'translate-x-1'}"
				/>
			</button>
			<input use:melt={$input} />
		</td>
	{/if}
	{#if allowEdit}
		<td class="whitespace-nowrap px-6 py-4 text-right text-sm font-medium">
			<div class="flex items-center justify-center gap-5">
				{#if formData !== undefined && currentUserGroups !== undefined}
					<EditButton
						item={'groups' in item ? item : undefined}
						{formData}
						{currentUserGroups}
						{users}
					/>
				{/if}

				<RemoveButton id={item.id} name={item.name} />
			</div>
		</td>
	{/if}
</tr>

// components/TableRow.vue
<script lang="ts" setup>
import { GiftItem } from "~~/lib/types";
import { Switch } from "@headlessui/vue";
import { useUserStore } from "~~/stores/user";

export interface Props {
    item: GiftItem;
    allowPurchased?: boolean;
    allowEdit?: boolean;
}

const userStore = useUserStore();

const props = withDefaults(defineProps<Props>(), {
    allowPurchased: false,
    allowEdit: false,
});
const emits = defineEmits<{
    (
        e: "switchPurchased",
        payload: { item: GiftItem; purchased: boolean }
    ): void;
    (e: "editItem", value: GiftItem): void;
    (e: "removeItem", value: GiftItem): void;
}>();

const formatPrice = (priceString: string | null) => {
    const defaultReturn = "-";

    if (!priceString) return defaultReturn;

    const sekFormatter = new Intl.NumberFormat("nl-NL", {
        style: "currency",
        currency: "SEK",
        maximumFractionDigits: 2,
    });
    const eurFormatter = new Intl.NumberFormat("nl-NL", {
        style: "currency",
        currency: "EUR",
        maximumFractionDigits: 2,
    });
    const usdFormatter = new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
        maximumFractionDigits: 2,
    });
    const defaultFormatter = new Intl.NumberFormat("default", {
        style: "decimal",
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    });

    const regex = /(?<code>(?:[$€])?)\s?(?<price>\d+(?:[,\.]\d+)?)/g;
    const matches = [...priceString.matchAll(regex)];

    if (!matches || !matches.length) return defaultReturn;

    const [_, currencyCode, price] = matches[0];
    const priceNumber = Number(price.replace(",", "."));

    switch (currencyCode) {
        case "SEK":
            return sekFormatter.format(priceNumber);
        case "€":
            return eurFormatter.format(priceNumber);
        case "$":
            return usdFormatter.format(priceNumber);
        default:
            return defaultFormatter.format(priceNumber);
    }
};
const formatLink = (linkString: string | null) => {
    if (!linkString) return "";

    const regex = /\b(?:http(?:s)?:\/\/)?((?:\w+\.)?\w+\.[\w\/\.\-_]*)/g;
    const matches = [...linkString.matchAll(regex)];

    if (!matches || !matches.length) return linkString;

    const [_, extractedLink] = matches[0];

    return extractedLink.replace("www.", "");
};
</script>

<template>
    <div
        :class="[
            'group grid last:border-none border-b border-gray-200 dark:border-gray-700',
            'purchased' in item &&
            item.purchased &&
            item.recipientId != userStore.currentUserId
                ? 'opacity-30 line-through decoration-2 decoration-current'
                : '',
            allowEdit
                ? 'grid-cols-table-5-sm sm:grid-cols-table-5'
                : 'grid-cols-table-4-sm sm:grid-cols-table-4',
        ]"
    >
        <div class="flex flex-col justify-center px-6 py-4 min-h-4rem">
            <h3 class="text-sm font-medium text-gray-900 dark:text-gray-100">
                {{ item.name }}
            </h3>
            <MarkdownDisplay
                v-if="item.notes"
                class="min-w-full text-gray-500 dark:text-gray-400"
            >
                {{ item.notes }}
            </MarkdownDisplay>
        </div>
        <div class="flex items-center min-w-full">
            <span
                class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400"
            >
                {{ formatPrice(item.price) }}
            </span>
        </div>
        <div class="flex items-center min-w-full">
            <a
                v-if="item.link"
                :href="item.link"
                target="_blank"
                rel="noopener noreferrer"
                class="px-6 py-4 whitespace-nowrap overflow-hidden overflow-ellipsis text-sm underline cursor-pointer font-normal text-primary-500 hover:text-primary-700"
            >
                {{ formatLink(item.link) }}
            </a>
        </div>
        <!-- FIXME -->
        <!-- <div class="flex items-center px-6 py-3">
			<div class="flex-shrink-0 h-10 w-10">
				<img
					v-if="item.pic"
					class="h-10 w-10 rounded-md"
					:src="item.pic[0].url"
					alt=""
				/>
			</div>
		</div> -->
        <div
            v-if="'purchased' in item && allowPurchased"
            class="flex justify-center items-center px-6 py-3"
        >
            <Switch
                :model-value="item.purchased"
                @update:model-value="
                    (evt) =>
                        emits('switchPurchased', {
                            item,
                            purchased: evt,
                        })
                "
                :class="
                    item.purchased
                        ? 'bg-success-500'
                        : 'bg-gray-200 dark:bg-gray-400'
                "
                class="relative inline-flex items-center h-6 rounded-full w-11"
            >
                <span class="sr-only">Item purchased</span>
                <span
                    :class="item.purchased ? 'translate-x-6' : 'translate-x-1'"
                    class="inline-block w-4 h-4 transform bg-white dark:bg-gray-100 rounded-full"
                />
            </Switch>
        </div>
        <div
            v-if="allowEdit"
            class="flex justify-center items-center px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
        >
            <EditButton :item="item" />
        </div>
        <div
            v-if="allowEdit"
            class="flex justify-center items-center px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
        >
            <RemoveButton :item="item" />
        </div>
    </div>
</template>
