// src/routes/login/+page.svelte
<script lang="ts">
	import Input from '$lib/components/Input.svelte';
	import { t } from '$lib/translations';
	import { superForm } from 'sveltekit-superforms/client';
	import Header from '../(auth)/Header.svelte';
	import type { PageData } from './$types';

	export let data: PageData;

	const { form, enhance, errors, constraints } = superForm(data.form);
</script>

<Header padding={false}>
	{$t('login.title')}

	<svelte:fragment slot="subtitle">
		{$t('login.description')}
	</svelte:fragment>
</Header>

<form class="formkit-form mt-8 space-y-6" method="POST" use:enhance>
	<Input
		name="username"
		type="text"
		label={$t('common.user.username')}
		bind:value={$form.username}
		placeholder={$t('common.user.username')}
		autocomplete="username"
		messages={$errors.username}
		aria-invalid={$errors.username ? 'true' : undefined}
		label-class="sr-only"
		input-class="rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
		message-class="mt-1 block w-full text-sm text-danger-400"
		{...$constraints.username}
	/>
	<Input
		name="password"
		type="password"
		label={$t('common.user.password')}
		bind:value={$form.password}
		placeholder={$t('common.user.password')}
		autocomplete="current-password"
		messages={$errors.password}
		aria-invalid={$errors.password ? 'true' : undefined}
		label-class="sr-only"
		input-class="rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
		message-class="mt-1 block w-full text-sm text-danger-400"
		{...$constraints.password}
	/>
	<Input
		type="submit"
		label={$t('common.signIn')}
		icon="lucide:lock"
		icon-class="h-4 w-4 text-primary-400 group-hover:text-primary-300 [&>svg]:w-full [&>svg]:h-full"
		input-class="group relative w-full flex justify-center item-center gap-3 py-2 px-4 border border-primary-700 text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
	/>
</form>

// src/pages/Login.vue
<template>
	<div
		class="
			min-h-full
			flex
			items-center
			justify-center
			py-12
			px-4
			sm:px-6
			lg:px-8
		"
	>
		<div class="max-w-md w-full space-y-8">
			<div>
				<h2
					class="
						mt-6
						text-center text-3xl
						font-extrabold
						text-gray-900
						dark:text-gray-100
					"
				>
					Please enter your password
				</h2>
			</div>
			<form class="mt-8 space-y-6" @submit.prevent="submitForm">
				<div class="rounded-md shadow-sm -space-y-px">
					<div>
						<label for="password" class="sr-only">Password</label>
						<input
							id="password"
							name="password"
							v-model="password"
							type="password"
							autocomplete="current-password"
							required
							class="
								appearance-none
								rounded-md
								relative
								block
								w-full
								px-3
								py-2
								border border-gray-300
								placeholder-gray-500
								text-gray-900
								focus:outline-none
								focus:ring-cyan-500
								focus:border-cyan-500
								focus:z-10
								sm:text-sm
							"
							placeholder="Password"
						/>
					</div>
				</div>

				<div>
					<button
						type="submit"
						class="
							group
							relative
							w-full
							flex
							justify-center
							py-2
							px-4
							text-sm
							font-medium
							rounded-md
							text-white
							bg-cyan-600
							hover:bg-cyan-700
							focus:outline-none
							focus:ring-2
							focus:ring-offset-2
							focus:ring-cyan-500
						"
					>
						<span
							class="
								absolute
								left-0
								inset-y-0
								flex
								items-center
								pl-3
							"
						>
							<LockClosedIcon
								class="
									h-5
									w-5
									text-cyan-500
									group-hover:text-cyan-400
								"
								aria-hidden="true"
							/>
						</span>
						Sign in
					</button>
				</div>
			</form>
		</div>
	</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { mapActions } from 'vuex';

import { LockClosedIcon } from '@heroicons/vue/outline';

export default defineComponent({
	components: { LockClosedIcon },
	data() {
		return {
			password: '',
		};
	},
	methods: {
		submitForm() {
			this.signIn(this.password)
				.then((id: string) => {
					localStorage.setItem('user', id);
                    this.$router.push('/overview')
				})
				.catch(() => {
					alert('Signing in was not succesful!');
				});
		},
		...mapActions('users', {
			signIn: 'signIn',
		}),
	},
});
</script>
