// pages/ideas.vue
<script lang="ts" setup>
import { Switch } from "@headlessui/vue";
import { useToast } from "vue-toastification/dist/index.mjs";

import { Color, GiftItem } from "~~/lib/types";
import { useGiftItemStore } from "~~/stores/gift-item";
import { useUserStore } from "~~/stores/user";

const giftItemStore = useGiftItemStore();
const userStore = useUserStore();

const toast = useToast();
const online = useOnline();

const isLoading = ref(true);
const showPartner = ref(false);
const headerColors: Color[] = [
    "pink",
    "purple",
    "indigo",
    "sky",
    "teal",
    "green",
    "yellow",
    "orange",
];

const filterItems = (item: GiftItem) => {
    const isGiftedByCurrentUser =
        "giftedById" in item &&
        item.giftedById != null &&
        (item.giftedById === userStore.currentUserId ||
            (showPartner.value &&
                item.giftedById === userStore.currentUser?.partnerId));

    return isGiftedByCurrentUser;
};

const switchPurchased = async (payload: {
    item: GiftItem;
    purchased: boolean;
}) => {
    try {
        if (!online.value) throw new Error("Not online");

        await giftItemStore.togglePurchased(payload);

        toast.success(
            `Changed purchase status of '${payload.item.name}' successfully!`
        );
    } catch (e) {
        if (e instanceof Error) {
            console.error(e);
            toast.error(
                `Saving purchase status was not successful! Reason: ${e.message}`
            );
        }
    }
};

onMounted(async () => {
    try {
        if (!online.value) throw new Error("Not online");

        await userStore.loadUsers();
        await giftItemStore.loadGiftItems();
    } catch (e) {
        if (e instanceof Error) {
            console.error(e);
            toast.error(
                `Loading data was not successful! Reason: ${e.message}`
            );
        }
    } finally {
        isLoading.value = false;
    }
});
</script>

<template>
    <NuxtLayout name="main">
        <Header>
            {{ $t("pages.ideas.title") }}

            <template #subtitle>
                {{ $t("pages.ideas.description") }}
            </template>
        </Header>

        <div class="container w-full flex justify-end gap-3 px-3">
            <span class="text-gray-500">{{
                $t("pages.ideas.showPartner")
            }}</span>
            <Switch
                v-model="showPartner"
                :class="
                    showPartner
                        ? 'bg-success-500'
                        : 'bg-gray-200 dark:bg-gray-400'
                "
                class="relative inline-flex items-center h-6 rounded-full w-11"
            >
                <span class="sr-only">Show partner</span>
                <span
                    :class="showPartner ? 'translate-x-6' : 'translate-x-1'"
                    class="inline-block w-4 h-4 transform bg-white dark:bg-gray-100 rounded-full"
                />
            </Switch>
        </div>

        <template v-if="giftItemStore.ideaList != null || !isLoading">
            <TableContainer>
                <template
                    v-for="(items, key, index) in giftItemStore.ideaList"
                    :key="key"
                >
                    <Table
                        :title="userStore.userEntities[key].name ?? null"
                        :header-color="headerColors[index]"
                        :show-bg-color="false"
                        :items="items.filter(filterItems) ?? null"
                        allow-purchased
                        allow-edit
                        is-collapsable
                        has-summary
                        @switchPurchased="switchPurchased"
                    />
                </template>
            </TableContainer>
        </template>

        <Icon
            v-else
            name="ph:spinner-gap-bold"
            class="animate-spin text-gray-900 dark:text-gray-100"
        />

        <AddIdeaButton />
    </NuxtLayout>
</template>

// src/routes/(auth)/ideas/+page.svelte
<script lang="ts">
	import AddButton from '$lib/components/AddButton.svelte';
	import { t } from '$lib/translations';
	import { createSwitch, melt } from '@melt-ui/svelte';
	import Header from '../Header.svelte';
	import Table from '../Table.svelte';
	import TableContainer from '../TableContainer.svelte';
	import type { PageData } from './$types';

	export let data: PageData;

	const {
		elements: { root, input },
		states: { checked: showPartner }
	} = createSwitch();
</script>

<Header>
	{$t('ideas.title')}

	<svelte:fragment slot="subtitle">
		{$t('ideas.description')}
	</svelte:fragment>
</Header>

<div class="container flex w-full justify-end gap-3 px-3">
	<label for="show-partner" class="text-gray-500">{$t('ideas.showPartner')}</label>
	<button
		use:melt={$root}
		id="show-partner"
		class="{$showPartner
			? 'bg-success-500'
			: 'bg-gray-200 dark:bg-gray-400'} relative inline-flex h-6 w-11 items-center rounded-full"
	>
		<span
			class="{$showPartner
				? 'translate-x-6'
				: 'translate-x-1'} inline-block h-4 w-4 transform rounded-full bg-white dark:bg-gray-100"
		/>
	</button>

	<input use:melt={$input} />
</div>

{#if data.ideaList}
	<TableContainer>
		{#each Object.keys(data.ideaList) as id, index (id)}
			{@const items = data.ideaList[id]}
			<Table
				title={items.at(0)?.recipient.name ?? undefined}
				headerHue={items.at(0)?.recipient.hue ?? undefined}
				showBgColor={false}
				items={items.filter(
					(item) =>
						item.giftedById != null &&
						(item.giftedById === data.user.id ||
							($showPartner && item.giftedById === data.user.partnerId))
				) ?? undefined}
				allowPurchased
				allowEdit
				isCollapsable
				hasSummary
				pageData={data}
			/>
		{/each}
	</TableContainer>
{/if}

<AddButton {...data} />
